version: "3.2"

services:
  web_php:
    container_name: ${PROJECT_NAME}_web_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - DB_MYSQL_HOST=db_mysql
      - DB_MYSQL_NAME=${DB_MYSQL_DATABASE_NAME}
      - DB_MYSQL_USER=${DB_MYSQL_USER}
      - DB_MEMCACHED_HOST=db_memcached
      - PHP_USER_ID=33
      - DB_REDIS_HOST=db_redis
    volumes:
      - .:/home/www
    depends_on:
      - "db_mysql"
    links:
      - db_mysql

  web_nginx:
    container_name: ${PROJECT_NAME}_web_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - .:/home/www

  db_mysql:
    container_name: ${PROJECT_NAME}_db_mysql
    restart: unless-stopped
    image: mysql:latest
    tty: true
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_MYSQL_DATABASE_NAME}
      - MYSQL_USER=${DB_MYSQL_USER}
      - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  db_memcached:
    container_name: ${PROJECT_NAME}_db_memcached
    image: memcached:latest

  db_redis:
    container_name: ${PROJECT_NAME}_db_redis
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    external:
      name: ${PROJECT_NAME}_mysql
  redis-data:
    external:
      name: ${PROJECT_NAME}_redis
  logvolume01: { }
